import type { Metadata } from "next";
import { M_PLUS_1 } from "next/font/google";
import "./globals.css";

const MPlus1Font = M_PLUS_1({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "生活関連施設 到達圏可視化マップ（仮）",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${MPlus1Font.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
